name: '@volta-cli/action'
description: 'Setup a Node.js environment with Volta'
author: 'Robert Jackson <me@rwjblue.com>'
inputs:
  volta-version:
    description: 'Version Spec of the volta version to use.  Examples: 0.6.x, 10.15.1, >=10.15.0'
    default: ''
  node-version:
    description: 'Version Spec of the node version to use.  Examples: 10.6.x, 10.15.1, >=10.15.0'
    default: ''
  npm-version:
    description: 'Version Spec of the npm version to use.  Examples: 7.5.x, 7.5.3, >=7.5.3'
    default: ''
  yarn-version:
    description: 'Version Spec of the yarn version to use.  Examples: 1.6.x, 10.15.1, >=10.15.0'
    default: ''
  variant:
    description: 'Specific variant we want to install. Example: providing the variant "linux-openssl-rhel", which will target installing the volta-{version}-linux-openssl-rhel.tar.gz tarball'
    default: ''
  registry-url:
    description: 'Optional registry to set up for auth. Will set the registry in a project level .npmrc file, and set up auth to read in from env.NODE_AUTH_TOKEN'
  scope:
    description: 'Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).'
  token:
    description: Used to avoid low rate limiting for cached tool downloads.  Since there's a default, this is typically not supplied by the user.
    default: ${{ github.token }}
  always-auth:
    description: 'Set always-auth in npmrc'
    default: 'false'
branding:
  icon: 'zap'
  color: 'yellow'
runs:
  using: 'node16'
  main: 'dist/index.js'
