name: '@volta-cli/action'
description: 'Setup a Node.js environment with Volta'
author: 'Robert Jackson <me@rwjblue.com>'
inputs:
  volta-version:
    description: 'Version Spec of the volta version to use.  Examples: 0.6.x, 10.15.1, >=10.15.0'
    default: ''
  node-version:
    description: 'Version Spec of the node version to use.  Examples: 10.6.x, 10.15.1, >=10.15.0'
    default: ''
  yarn-version:
    description: 'Version Spec of the yarn version to use.  Examples: 1.6.x, 10.15.1, >=10.15.0'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
